version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend-project/Dockerfile
      args:
        VITE_APP_ARG_VAR: "This is Arg"
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: ./backend-project/Dockerfile
    environment:
      ENV_VAR: "This is ENV"
    ports:
      - "3000:3000"
